import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import React from 'react';
import Footer from '@/components/footer';
import NavLayout from '@/components/navLayout';
import './globals.css';

const lato = Lato({ subsets: ['latin'], weight: ['100', '300', '400', '700', '900'] });

export const metadata: Metadata = {
  title: 'RHOMI',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={lato.className}>
        <NavLayout />
        {children}
        <Footer />
      </body>
    </html>
  );
}
